Updated IntegerToMoneyFormatHandler.php to fix process method
FriendsOfSylius/SyliusImportExportPlugin pull request #268
Opened 2021-09-03 07:19 UTC by Isabellebengrine

Replacing money_format function in process method

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?   | no
| Fixed tickets | #260  

Replaced the money_format function used in the process method to fix error when using the exporter button

2021-09-23 11:11 UTC, andriusvo requested changes

2021-09-23 11:11 UTC, andriusvo commented on src/Exporter/Transformer/Handler/IntegerToMoneyFormatHandler.php
> +        $locale = '';
use `LocaleContextInterface`

2021-09-23 11:11 UTC, andriusvo commented on src/Exporter/Transformer/Handler/IntegerToMoneyFormatHandler.php
> +        $fmt = new \NumberFormatter( $locale, \NumberFormatter::CURRENCY );
`$formatter` or `$numberFormatter`

2021-09-23 11:11 UTC, andriusvo commented on src/Exporter/Transformer/Handler/IntegerToMoneyFormatHandler.php
> +        $fmt = new \NumberFormatter( $locale, \NumberFormatter::CURRENCY );
no spaces inside braces

2021-09-23 11:11 UTC, andriusvo commented on src/Exporter/Transformer/Handler/IntegerToMoneyFormatHandler.php
> +        return $fmt->formatCurrency($value/100, "EUR");
`EUR` should not be hardcoded

2021-11-07 11:11 UTC, oallain requested changes
IMO, @Isabellebengrine you need to consider @andriusvo feedbacks.

2022-06-30 18:48 UTC, mbabker commented on src/Exporter/Transformer/Handler/IntegerToMoneyFormatHandler.php
> +        $locale = '';
Using `LocaleContextInterface` makes a lot of assumptions.  I just inlined a version of this handler to an app to un-block upgrading to PHP 8 and ended up hardcoding the locale in for now because the one spot this handler gets used in our app (order export) the handler lacks the context needed to get the locale from the order, which would mean that the field would be exported in the request's active locale (and in a multi-lingual store that may not be desired).

2022-06-30 18:52 UTC, mbabker commented on src/Exporter/Transformer/Handler/IntegerToMoneyFormatHandler.php
> +        return $fmt->formatCurrency($value/100, "EUR");
Same issue as I noted above, we don't have the context to get the right currency code to use here.

2023-01-03 10:36 UTC, oallain commented
Fixed in [0.23.0](https://github.com/FriendsOfSylius/SyliusImportExportPlugin/releases/tag/0.23.0)

2023-01-03 10:36 UTC, closed without merging